language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6




before_script:
  - composer install --dev --no-interaction
  - wget https://phar.phpunit.de/phpunit-4.8.phar

script: php phpunit-4.8.phar  --configuration tests/phpunit.xml
